#!/usr/bin/env node
const cp = require('child_process');

const eslintCWD = process.cwd();

function reject () {
  console.error('Verification failed. Please fix all errors and warnings and retry.'); // eslint-disable-line
  process.exit(1);
}

function accept () {
  console.error('Push validated ✓');
  process.exit(0);
}

process.stdout.write('Verifying git flags... ');

cp.exec('git config --global pull.rebase', null, (error, stdout, stderr) => {
  if (stdout.trim() !== 'true') {
    console.log('✗');
    console.log('Your pull.rebase setting is wrong. Please run the following command:\n');  // eslint-disable-line
    console.log('git config --global pull.rebase true\n');
    reject();
  } else {
    console.log('✓');

    process.stdout.write('Running sass-lint... ');

    cp.exec('npx sass-lint "src/**/*.scss "-v', null,
    (error, stdout, stderr) => {
      if (error || stdout.trim().length > 0) {
        console.log('✗');
        console.log(stdout);
        reject();
      } else {
        console.log('✓');

        process.stdout.write('Running eslint... ');
        process.chdir(eslintCWD);

        cp.exec('npx eslint src/', null,
          (error, stdout, stderr) => {
          if (error || stdout.trim().length > 0) {
            console.log('✗');
            console.log(stdout);
            reject();
          } else {
            console.log('✓');
            accept();
          }
        });
      }
    });
  }
});
